title: "Portfolio - Tariq Tamrabet"
logo: "assets/logo.png"
description: "Référent en gouvernance et qualité des données. Spécialisé en Data Governance, Data Engineering et automatisation des processus data."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
