# =============================
# üé® CONFIGURATION DU PORTFOLIO
# =============================

# --- Informations principales ---
title: "Portfolio ‚Äì Tariq Tamrabet"
name: "Tariq Tamrabet"
logo: ""C:\Users\tariq\Downloads\envato-labs-image-edit.png""        # chemin de ton logo
description: >
  R√©f√©rent en gouvernance et qualit√© des donn√©es, 
  sp√©cialis√© dans la structuration, la valorisation et 
  l‚Äôautomatisation des processus data. 
  D√©couvrez mes projets en Data Governance, Data Engineering et NLP.

# --- Liens externes ---
email: "tariq.tamrabet@hotmail.com"
linkedin: "https://linkedin.com/in/tariq-tamrabet"
github: "https://github.com/TariqTamrabet"

# --- Apparence du site ---
theme: jekyll-theme-cayman
show_downloads: false
google_analytics: false
markdown: kramdown


# --- Th√®me couleur (optionnel pour th√®mes Jekyll modernes) ---
# si tu veux forcer un style coh√©rent
colors:
  primary: "#005f99"
  secondary: "#00b894"
  background: "#f8f9fa"
  text: "#222"



